version: '3.8'

services:
  sqlserver:
    image: mysql:8.0
    container_name: sql_server_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  # Root password for MySQL
      MYSQL_DATABASE: ${DB_NAME}        # Name of the database to create
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql           # Persistent storage
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
  adminer:
    image: adminer
    container_name: project_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  db_data:
    # external: true
    # name: docker_config_sql_db_data