version: '3.8'

services:
  sqlserver:
    image: mysql:8.0
    container_name: sql_server_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_ja"  # Root password for MySQL
      MYSQL_DATABASE: "Smart_Street_Light_db"        # Name of the database to create
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql           # Persistent storage
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  db_data: